# Generated by Django 2.2.16 on 2023-02-17 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_follow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='creted',
            new_name='created',
        ),
    ]
