# Generated by Django 2.2.16 on 2023-02-18 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20230217_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(help_text='Введите комментарий в поле', null=True, verbose_name='Комментарий'),
        ),
    ]
